Makefile, Makefile.vars.mk, README.md, apis/generate.go, apis/postgresql/v1alpha1/postgresql_standalone_types.go, gen_sample.go, main.go, operator/operator.go, operator/standalone/controller.go, operator/standalone/webhook.go, operator_command.go, package/webhook/manifests.yaml, samples/admissionrequest.json, test/local.mk, test/provider-postgresql.yaml
* Adds support for building basic Webhooks for a resource. It works when installed with `make package-install` in local kind cluster.
* The crossplane packaging system is actually the one creating and configuring the webhook when installed via package. It creates and mounts the certificates for authentication by kubernetes.
=> Bootstrap Webhook support

charts/provider-postgresql/.helmignore, charts/provider-postgresql/Chart.yaml, charts/provider-postgresql/README.md, charts/provider-postgresql/templates/deployment.yaml
* Follow up of #27 
* This adds OPERATOR_NAMESPACE via downward API to the operator pod
=> Add OPERATOR_NAMESPACE env var

operator/standalone/webhook.go, operator/standalone/webhook_test.go
* Currently we don't support upgrading a PostgreSQL instance from one major version to another.
* This PR makes the field `.spec.forInstance.majorVersion` immutable via webhook.
=> Make the major version selector immutable

operator/standalone/webhook.go, operator/standalone/webhook_test.go
* Most storage backends do not support the decreased of already allocated PVs.
* This PR prevents specifying a storage capacity lower than already set.
Documentation added in #36 
=> Prevent storage capacity decrease

Makefile, docs/modules/ROOT/examples/standalone.yaml, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/references/standalone-api.adoc
* Adds an API spec reference page for `PostgresqlStandalone`.
Follows: #35 and #37
=> Add API reference page for PostgresqlStandalone

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/chart-lint.yml, .github/workflows/chart-release.yml, .gitignore, Makefile, apis/generate.go, charts/charts.mk, charts/provider-postgresql/Makefile, docs/modules/ROOT/pages/how-tos/create-releases.adoc, operator/generate.go, package/rbac/role.yaml, package/webhook/manifests.yaml
* Removes helm-chart-action and only uses plain chart-releaser
* Instead of merging a PR to `master`, a Helm chart release is triggered by pushing a Git tag like `provider-postgresql-x.y.z`
* `make generate` does no longer modify artifacts in `charts/` dir
* Chart artifacts can now be generated with `make chart-prepare`
=> Rework Helm chart release automation

charts/provider-postgresql/templates/webhook.yaml
* Adds a mutating webhook configuration to the template to add defaults to the specs.
* Follow a change in #38 
=> Add MutatingWebhook to chart

.github/render-charts.sh, .github/workflows/chart-lint.yml
* After #39 it makes sense to try to render charts in pipeline as a cheap linting step.
If the template doesn't render in the most default settings, there is a mistake (e.g. Helm value not interpretable)
=> Add linting step to render charts in GitHub actions

operator/standalone/create.go, operator/standalone/create_it_test.go, operator/standalone/create_test.go
Using Helm's `fullnameOverride` param we can set a static name.
The reason for doing so is that a lot of additional operators and controllers work with appending suffixes.
If we would continue using the same name as the instance CRD, we could encounter too long names and things may break.
Static names avoid this by setting a short-enough name.
The result is that every postgresql Pod in a namespace is called `postgresql-0` as an example (instead of something like `sv-postgresql-s-old-fire-7894-0` along with other resources like Services or PVCs.)
This is technically a breaking change, but since we haven't released anything working yet, it's fine.
=> Set static name for deployment in deployment namespace

operator/operatortest/envtest.go, operator/standalone/controller.go, operator/standalone/create.go, operator/standalone/create_it_test.go, operator/standalone/create_test.go, package/rbac/role.yaml
* When the helm release is ready, the operator fetches the credentials and service name and combines them into a single secret in the instance's namespace.
* Secret name is determined by `spec.writeConnectionSecretToRef.Name`.
* Secret gets an owner reference to the instance spec, so that deleting the instance spec also deletes the connection secret.
* All keys in the secret are in capitabls and prefixed with `POSTGRESQL_`.
* The following keys are exported:
* `POSTGRESQL_PASSWORD` (user password)
* `POSTGRESQL_POSTGRES_PASSWORD` (super user password)
* `POSTGRESQL_USER`
* `POSTGRESQL_DATABASE`
* `POSTGRESQL_SERVICE_NAME`
* `POSTGRESQL_SERVICE_URL`
* `POSTGRESQL_SERVICE_PORT`
Documentation: #55 
as they show up in …
=> Create connection secret when instance is ready

operator/helmvalues/helmvalues.go, operator/helmvalues/helmvalues_test.go, operator/standalone/create.go, operator/standalone/create_it_test.go, operator/standalone/create_test.go
We are not doing `type V map[string]interface{}` anymore as this breaks type assertion when deep-merging.
For example, if m is `V` then `ok` in `vals, ok := m.(map[string]interface{}` will be `false`.
To ensure that m is actually `map[string]interface{}`, we do a type alias with `type V = map[string]interface{}` instead (notice the `=` sign vs `type V map[string]interface{}`).
To group the available utility methods, I have moved everything into its own `helmvalues` package
=> Fix deep-merging of helmvalues if values are not 'map[string]interface'

charts/provider-postgresql/Chart.yaml, charts/provider-postgresql/README.md, charts/provider-postgresql/templates/secret.yaml
* Fixes a bug where rendering chart with `webhook.enabled` creates an invalid secret.
=> Don't render secret if 'webhook.enabled' is false

charts/provider-postgresql/Chart.yaml, charts/provider-postgresql/README.md, charts/provider-postgresql/templates/deployment.yaml
* Fixes a bug where in case if `webhook.enabled` is false, the volume and volumeMount in the pod spec is still rendered.
=> Don't render volumes if webhook is disabled

charts/provider-postgresql/Chart.yaml, charts/provider-postgresql/README.md, charts/provider-postgresql/templates/deployment.yaml
=> Don't render env var for setting TLS dir if webhook is disabled in chart

.github/workflows/chart-release.yml, .github/workflows/docs.yml, .github/workflows/release.yml, .gitignore, .goreleaser.yml, Makefile, charts/charts.mk, charts/provider-postgresql/Makefile, docs/antora.yml, docs/modules/ROOT/pages/tutorials/installation.adoc
* Adds the combined CRDs as a single file in `crds.yaml` as a downloadable artifact both in the normal GitHub release as well as any helm chart releases.
* Sets the git tag in `antora.yml`, so that any image or tag references can be made dynamic in the documentation.
Discussed in #64 
=> GH Actions: Distribute CRDs and provide tagged version in Antora

Makefile, test/k8up.mk, test/local.mk, test/minio-values.yaml
To prepare for Postgresql Backups with K8up we need S3 buckets running somewhere.
* Adds `make k8up-setup` to install K8up in latest version
* Adds `make minio-setup` to install Minio that can be used for local testing
* Adds `make s3-credentials` that copies the S3 user credentials to a namespace of your choosing with `bucket_namespace` variable (e.g. `make s3-credentials -e bucket_namespace=my-namespace`). May be used for later.
Doesn't do anything else for now as I don't know exactly yet what is required to get it running. Might change things in a follow-up PR.
=> Install K8up and Minio in local environment

Makefile, operator/operatortest/envtest.go, operator/standalone/controller.go, operator/standalone/create_it_test.go, operator/standalone/create_test.go, operator/standalone/delete.go, operator/standalone/delete_it_test.go
* Added business logic for a postgresql instance deletion.
=> Add instance deletion

charts/provider-postgresql/Chart.yaml, charts/provider-postgresql/README.md, charts/provider-postgresql/templates/clusterrole.yaml
* Updates the ClusterRole template after introduction of the new feature in #69 
=> Add K8up permissions to clusterrole

apis/postgresql/v1alpha1/connectionsecret.go, apis/postgresql/v1alpha1/connectionsecret_test.go, operator/standalone/create.go, operator/standalone/delete.go, operator/standalone/delete_it_test.go
* Closes #72
* Fixes panics where the name of the connection secret is empty in case it wasn't set by the webhook that sets defaults.
=> Fix deletion bugs in various places

operator/standalone/controller.go, operator/standalone/create.go
* Fixes #76 
* Fixes issues where the client uses a cache and that conflicts with updates and does not yield the expected results
=> Use controllerutil to insert or update objects

README.md, charts/provider-postgresql/Chart.yaml, charts/provider-postgresql/Makefile, charts/provider-postgresql/README.md, charts/provider-postgresql/templates/clusterrole.yaml
* Follow-up of #88 
* Adds the necessary permissions to perform PVC changes to the operator's SA
=> Add PVC permissions to cluster role in chart

charts/provider-postgresql/Chart.yaml, charts/provider-postgresql/Makefile, charts/provider-postgresql/README.md, charts/provider-postgresql/templates/clusterrole.yaml, charts/provider-postgresql/templates/clusterrolebinding.yaml, charts/provider-postgresql/templates/operator-clusterrole.yaml
* Adds `ClusterRole` resources that enable users to manage instances. They are added through [Role aggregation](https://kubernetes.io/docs/reference/access-authn-authz/rbac/#aggregated-clusterroles)
=> Add cluster role for users to chart

docs/modules/ROOT/assets/images/architecture.drawio.svg, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/explanations/architecture.adoc
* Adds page with a graph that displays how the operator deploys an instance.
=> Add page with high-level architecture
